# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'newGui.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import networkx as nx
import matplotlib.pyplot as plt

import Dijkstra


class Ui_MainWindow(object):

    def __init__(self):
        self.vertices = []
        self.aristas = []
        self.matrizAdyacencia = []
        self.grafo = nx.DiGraph()
        self.dijkstra = Dijkstra.Dijkstra()

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1208, 718)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.framePrincipal = QtWidgets.QFrame(self.centralwidget)
        self.framePrincipal.setGeometry(QtCore.QRect(0, 0, 1208, 718))
        self.framePrincipal.setStyleSheet("background-color: #fff")
        self.framePrincipal.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.framePrincipal.setFrameShadow(QtWidgets.QFrame.Raised)
        self.framePrincipal.setObjectName("framePrincipal")

        self.frameCantidad = QtWidgets.QFrame(self.framePrincipal)
        self.frameCantidad.setGeometry(QtCore.QRect(310, 30, 641, 601))
        self.frameCantidad.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameCantidad.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameCantidad.setObjectName("frameCantidad")

        self.LabelCantidadVertices = QtWidgets.QLabel(self.frameCantidad)
        self.LabelCantidadVertices.setGeometry(QtCore.QRect(170, 110, 291, 61))
        self.LabelCantidadVertices.setStyleSheet("border-radius: 10px;\n"
"font-size: 20px;\n"
"font: 20pt \"Times New Roman\";\n"
"font-weight: bold;\n"
"")
        self.LabelCantidadVertices.setAlignment(QtCore.Qt.AlignCenter)
        self.LabelCantidadVertices.setObjectName("LabelCantidadVertices")
        self.LineCantidadVertices = QtWidgets.QLineEdit(self.frameCantidad)
        self.LineCantidadVertices.setGeometry(QtCore.QRect(280, 250, 81, 31))
        self.LineCantidadVertices.setStyleSheet("border: 1px solid black;\n"
                                                "border-radius: 5px;\n"
                                                "font-size: 20px")
        self.LineCantidadVertices.setText("")
        self.LineCantidadVertices.setObjectName("LineCantidadVertices")
        self.pushButtonCantidad = QtWidgets.QPushButton(self.frameCantidad)
        self.pushButtonCantidad.setGeometry(QtCore.QRect(230, 370, 185, 50))
        self.pushButtonCantidad.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButtonCantidad.setStyleSheet("background-color: #0ea5e9;\n"
"border-radius: 10px;\n"
"color: #fff;\n"
"font-size: 20px")
        self.pushButtonCantidad.setObjectName("pushButtonCantidad")
        self.pushButtonCantidad.clicked.connect(self.mostrarFrameEtiquetas)
        self.LabelNotaCantidad = QtWidgets.QLabel(self.frameCantidad)
        self.LabelNotaCantidad.setGeometry(QtCore.QRect(150, 450, 351, 101))
        self.LabelNotaCantidad.setStyleSheet("font-size: 15px;\n"
"color: rgb(36, 36, 36);\n"
"font-weight: bold;\n"
"border-radius: 10px")
        self.LabelNotaCantidad.setAlignment(QtCore.Qt.AlignCenter)
        self.LabelNotaCantidad.setWordWrap(True)
        self.LabelNotaCantidad.setObjectName("LabelNotaCantidad")

        self.frameEtiquetas = QtWidgets.QFrame(self.framePrincipal)
        self.frameEtiquetas.setGeometry(QtCore.QRect(310, 30, 641, 601))
        self.frameEtiquetas.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameEtiquetas.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameEtiquetas.setObjectName("frameEtiquetas")
        self.frameEtiquetas.setVisible(False)

        self.LabelNombreEtiquetas = QtWidgets.QLabel(self.frameEtiquetas)
        self.LabelNombreEtiquetas.setGeometry(QtCore.QRect(180, 50, 291, 61))
        self.LabelNombreEtiquetas.setStyleSheet("border-radius: 10px;\n"
"font-size: 20px;\n"
"font: 20pt \"Times New Roman\";\n"
"font-weight: bold;\n"
"")
        self.LabelNombreEtiquetas.setAlignment(QtCore.Qt.AlignCenter)
        self.LabelNombreEtiquetas.setObjectName("LabelNombreEtiquetas")
        self.pushButtonGenerarMatriz = QtWidgets.QPushButton(self.frameEtiquetas)
        self.pushButtonGenerarMatriz.setGeometry(QtCore.QRect(200, 390, 250, 54))
        self.pushButtonGenerarMatriz.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButtonGenerarMatriz.setStyleSheet("background-color: #0ea5e9;\n"
"border-radius: 10px;\n"
"color: #fff;\n"
"font-size: 20px")
        self.pushButtonGenerarMatriz.setObjectName("pushButtonGenerarMatriz")
        self.pushButtonGenerarMatriz.clicked.connect(self.mostrarFrameMatriz)
        self.LabelNotaEtiquetas = QtWidgets.QLabel(self.frameEtiquetas)
        self.LabelNotaEtiquetas.setGeometry(QtCore.QRect(150, 450, 351, 101))
        self.LabelNotaEtiquetas.setStyleSheet("font-size: 15px;\n"
                                             "color: rgb(36, 36, 36);\n"
                                             "font-weight: bold;\n"
                                             "border-radius: 10px")
        self.LabelNotaEtiquetas.setAlignment(QtCore.Qt.AlignCenter)
        self.LabelNotaEtiquetas.setWordWrap(True)
        self.LabelNotaEtiquetas.setObjectName("LabelNotaEtiquetas")


        self.frameMatrizAdyacencia = QtWidgets.QFrame(self.framePrincipal)
        self.frameMatrizAdyacencia.setEnabled(True)
        self.frameMatrizAdyacencia.setGeometry(QtCore.QRect(0, 0, 621, 531))
        self.frameMatrizAdyacencia.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameMatrizAdyacencia.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameMatrizAdyacencia.setObjectName("frameMatrizAdyacencia")
        self.frameMatrizAdyacencia.setVisible(False)


        self.LabelMatrizAdyacencia = QtWidgets.QLabel(self.frameMatrizAdyacencia)
        self.LabelMatrizAdyacencia.setGeometry(QtCore.QRect(170, 10, 291, 61))
        self.LabelMatrizAdyacencia.setStyleSheet("border-radius: 10px;\n"
"font-size: 20px;\n"
"font: 20pt \"Times New Roman\";\n"
"font-weight: bold;\n"
"")
        self.LabelMatrizAdyacencia.setAlignment(QtCore.Qt.AlignCenter)
        self.LabelMatrizAdyacencia.setObjectName("LabelMatrizAdyacencia")

        self.LabelNotaMatrizAdyacencia = QtWidgets.QLabel(self.frameMatrizAdyacencia)
        self.LabelNotaMatrizAdyacencia.setGeometry(QtCore.QRect(20, 432, 200, 100))
        self.LabelNotaMatrizAdyacencia.setStyleSheet("font-size: 13px;\n"
                                             "color: rgb(36, 36, 36);\n"
                                             "font-weight: bold;\n"
                                             "border-radius: 10px")
        self.LabelNotaMatrizAdyacencia.setAlignment(QtCore.Qt.AlignCenter)
        self.LabelNotaMatrizAdyacencia.setWordWrap(True)
        self.LabelNotaMatrizAdyacencia.setObjectName("LabelNotaCantidad")
        self.pushButtonGenerarGrafo = QtWidgets.QPushButton(self.frameMatrizAdyacencia)
        self.pushButtonGenerarGrafo.setGeometry(QtCore.QRect(220, 460, 221, 41))
        self.pushButtonGenerarGrafo.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButtonGenerarGrafo.setStyleSheet("background-color: #0ea5e9;\n"
                                                  "border-radius: 10px;\n"
                                                  "color: #fff;\n"
                                                  "font-size: 20px;\n"
                                                  "")
        self.pushButtonGenerarGrafo.setObjectName("pushButtonGenerarGrafo")
        self.pushButtonGenerarGrafo.clicked.connect(self.mostrarGrafoDijkstra)

        self.frameImagenGrafo = QtWidgets.QFrame(self.framePrincipal)
        self.frameImagenGrafo.setGeometry(QtCore.QRect(self.frameMatrizAdyacencia.width(),0, 581, 531))
        self.frameImagenGrafo.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameImagenGrafo.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameImagenGrafo.setObjectName("frameImagenGrafo")
        self.frameImagenGrafo.setVisible(False)



        self.frameFormDijkstra = QtWidgets.QFrame(self.framePrincipal)
        self.frameFormDijkstra.setGeometry(QtCore.QRect(0, 535, 621, 190))
        self.frameFormDijkstra.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameFormDijkstra.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameFormDijkstra.setObjectName("frameFormDijkstra")
        self.frameFormDijkstra.setVisible(False)

        self.LabelAlgoritmoDijkstra = QtWidgets.QLabel(self.frameFormDijkstra)
        self.LabelAlgoritmoDijkstra.setGeometry(QtCore.QRect(170, 0, 291, 61))
        self.LabelAlgoritmoDijkstra.setStyleSheet("border-radius: 10px;\n"
"font-size: 20px;\n"
"font: 20pt \"Times New Roman\";\n"
"font-weight: bold;\n"
"")
        self.LabelAlgoritmoDijkstra.setAlignment(QtCore.Qt.AlignCenter)
        self.LabelAlgoritmoDijkstra.setObjectName("LabelAlgoritmoDijkstra")
        self.LineDijkstraOrigen = QtWidgets.QLineEdit(self.frameFormDijkstra)
        self.LineDijkstraOrigen.setGeometry(QtCore.QRect(100, 90, 81, 31))
        self.LineDijkstraOrigen.setStyleSheet("border: 1px solid black;\n"
                                          "border-radius: 5px;\n"
                                         "font-size: 17px")
        self.LineDijkstraOrigen.setText("")
        self.LineDijkstraOrigen.setObjectName("LineDijkstraOrigen")
        self.LineDijkstraDestino = QtWidgets.QLineEdit(self.frameFormDijkstra)
        self.LineDijkstraDestino.setGeometry(QtCore.QRect(280, 90, 81, 31))
        self.LineDijkstraDestino.setStyleSheet("border: 1px solid black;\n"
                                          "border-radius: 5px;\n"
                                         "font-size: 17px")
        self.LineDijkstraDestino.setText("")
        self.LineDijkstraDestino.setObjectName("LineDijkstraDestino")
        self.pushConsultarDijkstra = QtWidgets.QPushButton(self.frameFormDijkstra)
        self.pushConsultarDijkstra.setGeometry(QtCore.QRect(440, 90, 131, 31))
        self.pushConsultarDijkstra.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushConsultarDijkstra.setStyleSheet("background-color: #0ea5e9;\n"
"border-radius: 10px;\n"
"color: #fff;\n"
"font-size: 20px;\n"
"")
        self.pushConsultarDijkstra.setObjectName("pushConsultarDijkstra")
        self.pushConsultarDijkstra.clicked.connect(self.algoritmoDijkstra)
        self.LabelDijkstraOrigen = QtWidgets.QLabel(self.frameFormDijkstra)
        self.LabelDijkstraOrigen.setGeometry(QtCore.QRect(10, 80, 71, 41))
        self.LabelDijkstraOrigen.setStyleSheet("border-radius: 10px;\n"
"font: 15pt \"Times New Roman\";\n"
"font-weight: bold;\n"
"")
        self.LabelDijkstraOrigen.setAlignment(QtCore.Qt.AlignCenter)
        self.LabelDijkstraOrigen.setObjectName("LabelDijkstraOrigen")
        self.LabelDijkstraDestino = QtWidgets.QLabel(self.frameFormDijkstra)
        self.LabelDijkstraDestino.setGeometry(QtCore.QRect(200, 80, 71, 41))
        self.LabelDijkstraDestino.setStyleSheet("border-radius: 10px;\n"
"font: 15pt \"Times New Roman\";\n"
"font-weight: bold;\n"
"")
        self.LabelDijkstraDestino.setAlignment(QtCore.Qt.AlignCenter)
        self.LabelDijkstraDestino.setObjectName("LabelDijkstraDestino")

        self.frameResultadoDijkstra = QtWidgets.QFrame(self.framePrincipal)
        self.frameResultadoDijkstra.setGeometry(QtCore.QRect(self.frameFormDijkstra.width(), 500, 581, 181))
        self.frameResultadoDijkstra.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameResultadoDijkstra.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameResultadoDijkstra.setObjectName("frameResultadoDijkstra")
        self.frameResultadoDijkstra.setVisible(False)

        self.LabelResultadoDijkstra = QtWidgets.QLabel(self.frameResultadoDijkstra)
        self.LabelResultadoDijkstra.setGeometry(QtCore.QRect(30, 10, 581, 181))
        self.LabelResultadoDijkstra.setStyleSheet("border-radius: 10px;\n "
                                                  "font-size: 20px;\n"
                                                  "font: 20pt \"Times New Roman\";\n"
                                                  "font-weight: bold;\n"
                                                  "")
        self.LabelResultadoDijkstra.setText("")
        self.LabelResultadoDijkstra.setAlignment(QtCore.Qt.AlignCenter)
        self.LabelResultadoDijkstra.setWordWrap(True)
        self.LabelResultadoDijkstra.setObjectName("LabelResultadoDijkstra")





        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.LabelCantidadVertices.setText(_translate("MainWindow", "Cantidad de Vertices"))
        self.pushButtonCantidad.setText(_translate("MainWindow", "Establecer Cantidad"))
        self.LabelNotaCantidad.setText(_translate("MainWindow", "La cantidad debera ser un numero entero mayor a uno y menor o igual a 10"))
        self.LabelNombreEtiquetas.setText(_translate("MainWindow", "Nombre de las Etiquetas"))
        self.pushButtonGenerarMatriz.setText(_translate("MainWindow", "Generar Matriz Adyacencia"))
        self.LabelNotaEtiquetas.setText(_translate("MainWindow", "No deben haber etiquetas repetidas o vacias"))
        self.pushButtonGenerarGrafo.setText(_translate("MainWindow", "Construir Grafo"))
        self.LabelMatrizAdyacencia.setText(_translate("MainWindow", "Matriz de Adyacencia"))
        #self.LabelFilaPeso.setText(_translate("MainWindow", "a"))
        #self.LabelColumnaPeso.setText(_translate("MainWindow", "a"))
        self.LabelAlgoritmoDijkstra.setText(_translate("MainWindow", "Algoritmo de Dijkstra"))
        self.LabelNotaMatrizAdyacencia.setText(_translate("MainWindow", "Valores no numericos seran tomados como cero"))
        self.pushConsultarDijkstra.setText(_translate("MainWindow", "Consultar"))
        self.LabelDijkstraOrigen.setText(_translate("MainWindow", "Origen:"))
        self.LabelDijkstraDestino.setText(_translate("MainWindow", "Destino:"))

    def mostrarFrameEtiquetas(self):
        # Si el el campo es vacio o menor a 1
        if self.LineCantidadVertices.text() == '':
            return
        else:
            try:
                cantidadEtiquetas = int(self.LineCantidadVertices.text())
                if (cantidadEtiquetas <= 1):
                    return
            except:
                return

        # Escondemos los otros frames
        self.frameCantidad.setVisible(False)
        self.frameEtiquetas.setVisible(True)

        cantidadVertices = int(self.LineCantidadVertices.text())
        if cantidadVertices > 10: cantidadVertices = 10
        segundaFila = 0
        for primeraFila in range(cantidadVertices):
            self.LineEtiqueta = QtWidgets.QLineEdit(self.frameEtiquetas)
            if(primeraFila<5):
                self.LineEtiqueta.setGeometry(QtCore.QRect(100+(primeraFila*90), 140, 81, 31))
            else:
                self.LineEtiqueta.setGeometry(QtCore.QRect(100+(segundaFila*90), 190, 81, 31))
                segundaFila+=1
            self.LineEtiqueta.setStyleSheet("border: 1px solid black;\n"
                                            "border-radius: 5px;\n"
                                            "font-size: 20px"
                                            )
            self.LineEtiqueta.setText("")
            self.LineEtiqueta.setObjectName("LineEtiqueta")

            # guardamos las referencia de los lineedit en un vector vertice
            self.vertices.append(self.LineEtiqueta)

        for i in range(cantidadVertices):
            self.vertices[i].show()
            # Evento para cambiar el valor de texto del vector vertice
            self.vertices[i].textChanged[str]




    def mostrarFrameMatriz(self):

        #Validacion entrada de etiquetas
        repetidos = False
        vacios = False
        for vertice in range(len(self.vertices)):
            contadorRepeticiones = 0
            if self.vertices[vertice].text() != '':
                for comprobacion in range(len(self.vertices)):
                    if self.vertices[vertice].text() == self.vertices[comprobacion].text():
                        contadorRepeticiones += 1
                        if contadorRepeticiones > 1:
                            repetidos = True
                            break
            else:
                vacios = True

        if repetidos or vacios: return

        #Encondemos y mostramos los frames a conveni
        self.frameEtiquetas.setVisible(False)
        self.frameMatrizAdyacencia.setVisible(True)

        #Mostramos etiquetas
        for i in range(len(self.vertices)):
            self.LabelFilaPeso = QtWidgets.QLabel(self.frameMatrizAdyacencia)
            self.LabelFilaPeso.setGeometry(QtCore.QRect(30, 100+(i*30), 31, 31))
            self.LabelFilaPeso.setStyleSheet("border-radius: 10px;\n"
                                             "font: 14pt \"Times New Roman\";\n"
                                             "font-weight: bold;\n"
                                             "")
            self.LabelFilaPeso.setAlignment(QtCore.Qt.AlignCenter)
            self.LabelFilaPeso.setText(self.vertices[i].text())
            self.LabelFilaPeso.setObjectName("LabelFilaPeso")
            self.LabelFilaPeso.show()

            self.LabelColumnaPeso = QtWidgets.QLabel(self.frameMatrizAdyacencia)
            self.LabelColumnaPeso.setGeometry(QtCore.QRect(60+(i*30), 70, 31, 31))
            self.LabelColumnaPeso.setStyleSheet("border-radius: 10px;\n"
                                                "font: 14pt \"Times New Roman\";\n"
                                                "font-weight: bold;\n"
                                                "")
            self.LabelColumnaPeso.setAlignment(QtCore.Qt.AlignCenter)
            self.LabelColumnaPeso.setText(self.vertices[i].text())
            self.LabelColumnaPeso.setObjectName("LabelColumnaPeso")
            self.LabelColumnaPeso.show()

            # guardamos el texto en el vector de aristas
            text = self.vertices[i].text()
            self.vertices[i].deleteLater()
            self.vertices[i] = text
            self.grafo.add_node(text)



        filas = columnas = len(self.vertices)
        self.matrizAdyacencia = [[None] * (filas) for i in range(columnas)]

        for fila in range(filas):
            for columna in range(columnas):
                # Pinta los lineedit de la matriz de adyacencia
                self.LinePeso = QtWidgets.QLineEdit(self.frameMatrizAdyacencia)
                self.LinePeso.setGeometry(QtCore.QRect(60+(columna*30), 100+(fila*30), 29, 29))
                self.LinePeso.setStyleSheet("border: 1px solid black;\n"
                                          "border-radius: 5px;\n"
                                         "font-size: 17px")
                self.LinePeso.setText("0")
                self.LinePeso.setObjectName("LinePeso")

                # guardando referencia de los line edit en una matriz
                self.matrizAdyacencia[fila][columna] = self.LinePeso

        for fila in range(filas):
            for columna in range(columnas):
                self.matrizAdyacencia[fila][columna].show()
                # Evento para cambiar el valor de texto de la matriz adyacencia
                self.matrizAdyacencia[fila][columna].textChanged[str]

    def mostrarGrafoDijkstra(self):
        self.frameFormDijkstra.setVisible(True)
        self.frameMatrizAdyacencia.setEnabled(False)

        columnas = filas = len(self.matrizAdyacencia)

        for fila in range(filas):
            for columna in range(columnas):
                cantidad = self.matrizAdyacencia[fila][columna].text()
                try:
                    pesoArista =  int(cantidad)
                    if(pesoArista < 0):
                        self.matrizAdyacencia[fila][columna].setText(f"{abs(pesoArista)}")
                except:
                    self.matrizAdyacencia[fila][columna].setText('0')

        for fila in range(filas):
            for columna in range(columnas):
                self.matrizAdyacencia[fila][columna].setEnabled(False)
                cantidadArista = self.matrizAdyacencia[fila][columna].text()

                # guardamos los valores en la matriz de adyacencia
                self.matrizAdyacencia[fila][columna] = int(cantidadArista)

        for vertice in range(len(self.vertices)):
            for arista in range(len(self.vertices)):
                if self.matrizAdyacencia[vertice][arista] != 0:  # si el peso es diferente de cero
                    inicio = self.vertices[vertice]
                    final = self.vertices[arista]
                    peso = self.matrizAdyacencia[vertice][arista]
                    # agregamos las aristas  ej; [a,b,1]
                    self.aristas.append([inicio, final, peso])
                    self.grafo.add_edge(inicio, final, weight=peso)
        self.guardarImagenGrafo()

        print(self.aristas)
        self.frameImagenGrafo.setVisible(True)
        self.frameResultadoDijkstra.setVisible(True)

        # pintamos el grafo
        self.image = QtGui.QPixmap('./assets/Grafo.png')
        self.LabelImageGrafo = QtWidgets.QLabel(self.frameImagenGrafo)
        self.LabelImageGrafo.setPixmap(self.image)
        self.LabelImageGrafo.show()


    def guardarImagenGrafo(self):
        pos = nx.circular_layout(self.grafo)
        nx.draw_networkx(self.grafo, pos, with_labels=True, font_weight='bold', font_color='white')
        labels = nx.get_edge_attributes(self.grafo, 'weight')

        nx.draw_networkx_edges(self.grafo, pos, arrowsize=10, arrowstyle='->', width=1 )
        nx.draw_networkx_nodes(self.grafo, pos, node_size=300, node_color='#0284C7')
        nx.draw_networkx_edge_labels(self.grafo, pos, edge_labels=labels)

        ax = plt.gca()
        plt.axis('off')
        #ax.margins(0.6)

        plt.savefig('assets/grafo.png', transparent=True, bbox_inches='tight', pad_inches=1)

    def algoritmoDijkstra(self):
        if self.LineDijkstraOrigen.text() and self.LineDijkstraDestino != '':
            self.dijkstra.setMatrizOrigenDestino(self.aristas, self.LineDijkstraOrigen.text(), self.LineDijkstraDestino.text())
            self.dijkstra.dijkstra()
            mensaje = self.dijkstra.getVisitados()
            print(mensaje)
            self.LabelResultadoDijkstra.setText(mensaje)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
